name: Docker VaultWarden

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: git clone
      run: |
        git clone https://github.com/Timshel/vaultwarden
    - name: docker login
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin  
    - name: docker buildx multiarch
      run: |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --name multiarch --driver docker-container --use
        docker buildx inspect --bootstrap
    - name: docker build
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      run: |
        docker buildx build . -t $DOCKER_USER/vaultwarden-sso:main --platform linux/arm64,linux/amd64 --push
